// How the project's Reference Docs are organized in the Docs sidebar: a
// strict parent → child tree of categories (and sub-categories) with the
// docs as leaves — base guidelines apart from component specs, engineering
// references and process docs. Docs not placed here (e.g. new ones) fall
// into a category by their type; docs generated by Design System Updates
// get their own branch.

export const DOC_TREE = [
  {
    id: 'guidelines',
    label: 'Guidelines',
    children: [
      { id: 'brand', label: 'Brand', docs: ['doc-brand-guidelines', 'doc-copy'] },
      {
        id: 'foundations',
        label: 'Foundations',
        docs: ['doc-color-tokens', 'doc-type-scale', 'doc-spacing', 'doc-motion', 'doc-iconography', 'doc-dark-mode'],
      },
    ],
  },
  {
    id: 'components',
    label: 'Component specs',
    children: [
      { id: 'inputs', label: 'Actions & inputs', docs: ['doc-button-spec', 'doc-input-spec'] },
      { id: 'containers', label: 'Containers & overlays', docs: ['doc-card-spec', 'doc-modal-spec'] },
    ],
  },
  {
    id: 'engineering',
    label: 'Engineering',
    docs: ['doc-api-contract', 'doc-api-errors', 'doc-analytics'],
    children: [
      { id: 'backend', label: 'Backend', docs: ['doc-backend-architecture', 'doc-backend-api', 'doc-backend-jobs', 'doc-backend-operations'] },
      { id: 'database', label: 'Database', docs: ['doc-database-schema'] },
    ],
  },
  {
    id: 'process',
    label: 'Process',
    children: [
      { id: 'document-updates', label: 'Document updates', generated: true },
      { id: 'team', label: 'Team', docs: ['doc-onboarding', 'doc-review', 'doc-handoff'] },
      { id: 'quality', label: 'Quality & release', docs: ['doc-a11y', 'doc-release', 'doc-naming'] },
    ],
  },
]

// Where an unplaced doc goes, by its type.
const FALLBACK = { design: 'foundations', spec: 'inputs', doc: 'team' }

// Include leaf categories and parents that already contain documents.
export function documentCategoryOptions(nodes = DOC_TREE, trail = []) {
  return nodes.flatMap((node) => {
    const path = [...trail, node.label]
    const own = !node.children?.length || node.docs ? [{ id: node.id, path }] : []
    return [...own, ...documentCategoryOptions(node.children ?? [], path)]
  })
}

export function validDocumentCategory(id) {
  return documentCategoryOptions().some((category) => category.id === id)
}

export function suggestedDocumentCategory(update, affectedDocs = []) {
  if (validDocumentCategory(update.categoryId)) return update.categoryId
  const text = [update.title, update.summary, update.file, ...(update.changes ?? []).map((change) => change.label)].filter(Boolean).join(' ').toLowerCase()
  const topics = [
    ['database', /database|schema|migration|sql|데이터베이스|스키마/],
    ['backend', /backend|server|api|endpoint|auth|백엔드/],
    ['containers', /card|modal|overlay|dialog/],
    ['inputs', /button|input|checkbox|toggle|버튼/],
    ['foundations', /token|color|spacing|radius|typograph|font|motion|색상/],
    ['brand', /brand|copywriting|브랜드/],
    ['quality', /release|accessibility|a11y|quality|배포/],
    ['team', /onboarding|handoff|review|process|온보딩/],
  ]
  const topic = topics.find(([, pattern]) => pattern.test(text))
  if (topic) return topic[0]
  const tree = buildDocTree(affectedDocs)
  const path = affectedDocs[0] && docPath(tree, affectedDocs[0].id)
  return documentCategoryOptions().find((category) => category.path.join('/') === path?.join('/'))?.id ?? 'team'
}

function collectIds(nodes, into = new Set()) {
  for (const node of nodes) {
    node.docs?.forEach((id) => into.add(id))
    if (node.children) collectIds(node.children, into)
  }
  return into
}

// The tree with each node's docs resolved: `{ id, label, docs: [doc],
// children: [...] }`, empty branches dropped.
export function buildDocTree(referenceDocs) {
  const placed = collectIds(DOC_TREE)
  const byId = new Map(referenceDocs.map((d) => [d.id, d]))
  const extras = {}
  for (const doc of referenceDocs) {
    if (placed.has(doc.id)) continue
    const target = validDocumentCategory(doc.categoryId) ? doc.categoryId
      : (doc.docUpdateId || doc.dsUpdateId) ? 'document-updates' : (FALLBACK[doc.type] ?? 'team')
    ;(extras[target] ??= []).push(doc)
  }

  function resolve(node) {
    const docs = [...(node.docs ?? []).map((id) => byId.get(id)).filter(Boolean), ...(extras[node.id] ?? [])]
    const children = (node.children ?? []).map(resolve).filter((c) => c.docs.length || c.children.length)
    return { id: node.id, label: node.label, docs, children }
  }

  return DOC_TREE.map(resolve).filter((n) => n.docs.length || n.children.length)
}

// Count of docs under a node, sub-categories included.
export function countDocs(node) {
  return node.docs.length + node.children.reduce((sum, c) => sum + countDocs(c), 0)
}

// The category path to a doc, e.g. ['Guidelines', 'Foundations'].
export function docPath(tree, docId, trail = []) {
  for (const node of tree) {
    const here = [...trail, node.label]
    if (node.docs.some((d) => d.id === docId)) return here
    const found = docPath(node.children, docId, here)
    if (found) return found
  }
  return null
}

// Search includes visible document content and its category path.
export function searchDocs(docs, query) {
  const terms = query.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean)
  if (!terms.length) return docs
  const tree = buildDocTree(docs)
  return docs.filter((doc) => {
    const text = [doc.title, doc.summary, ...(doc.searchKeywords ?? []),
      ...(docPath(tree, doc.id) ?? []),
      ...(doc.blocks ?? []).flatMap((block) => [block.text, ...(block.items ?? []),
        ...(block.columns ?? []), ...(block.rows ?? []).flat(), block.code])]
      .filter(Boolean).join(' ').toLocaleLowerCase()
    return terms.every((term) => text.includes(term))
  })
}
